### ISSUE TITLE
powerful-table

### ISSUE THREAD

**Issue by nikijm** [peng-xiao-shuai/vite-vue-admin#3]
请问有powerful-table源码吗，readme里面链接访问不了

**Comment by peng-xiao-shuai** [comment]
你可以直接访问这个 https://github.com/peng-xiao-shuai/el-plus-powerful-table  也就是我的仓库，更多powerful-table功能可以 访问 https://peng-xiao-shuai.github.io/el-plus-powerful-table/ 查看演示

> 有强大的-table源码吗，readme里面的请求不能访问
